demo:
  user-id: 1000
spring:
  application:
    admin:
      enabled: true
    name: spring-boot-demo
#  security:
#    user:
#      name: user
#      password: 123456
#      roles: USER

#debug: true
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    status-page-url-path: /health
  client:
    registry-fetch-interval-seconds: 10 #表示eureka client间隔多久去拉取服务注册信息 在网关使用
    service-url:
      defaultZone: http://106.14.187.241:5100/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 9876
management:
  endpoint:
    my:
      enabled: true
    beans:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "*"  # 代表所有
          - shutdown
      #          - beans
      #          - my
      #          - loggers
      exclude:
        - loggers
      base-path: /actuator
      path-mapping:
        my: /myMap    # 将@Endpoint(id = "my")中的my对应的路径做映射，这个时候原本的my就不可用了