server:
    port: 5301
spring:
    application:
        name: spring-cloud-provider
feign:
  hystrix:
    enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    status-page-url-path: /health
  client:
    registry-fetch-interval-seconds: 10 #表示eureka client间隔多久去拉取服务注册信息 在网关使用
    service-url:
      defaultZone: http://127.0.0.1:5100/eureka/
    fetch-registry: true
    register-with-eureka: true
debug: true
